//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Modul_ucheta
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Оказ услуг.
    /// </summary>
    // *** Start programmer edit section *** (ОказУслуг CustomAttributes)

    // *** End programmer edit section *** (ОказУслуг CustomAttributes)
    [AutoAltered()]
    [Caption("ОказаниеУслуг")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОказУслугE", new string[] {
            "Дата as \'Дата\'",
            "ВремяКонсульт as \'Время консульт\'",
            "ЕдВремени as \'Ед времени\'",
            "Услуги as \'Услуги\'",
            "Услуги.ЗатрВремя",
            "Договор as \'Договор\'",
            "Договор.Длительность as \'Длительность\'"})]
    [MasterViewDefineAttribute("ОказУслугE", "Услуги", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [MasterViewDefineAttribute("ОказУслугE", "Договор", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Номер")]
    public class ОказУслуг : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата;
        
        private double fВремяКонсульт;
        
        private IIS.Modul_ucheta.ЕдВремени fЕдВремени;
        
        private IIS.Modul_ucheta.Услуги fУслуги;
        
        private IIS.Modul_ucheta.Договор fДоговор;
        
        private IIS.Modul_ucheta.РасчетОстВрем fРасчетОстВрем;
        
        // *** Start programmer edit section *** (ОказУслуг CustomMembers)

        // *** End programmer edit section *** (ОказУслуг CustomMembers)

        
        /// <summary>
        /// ВремяКонсульт.
        /// </summary>
        // *** Start programmer edit section *** (ОказУслуг.ВремяКонсульт CustomAttributes)

        // *** End programmer edit section *** (ОказУслуг.ВремяКонсульт CustomAttributes)
        public virtual double ВремяКонсульт
        {
            get
            {
                // *** Start programmer edit section *** (ОказУслуг.ВремяКонсульт Get start)

                // *** End programmer edit section *** (ОказУслуг.ВремяКонсульт Get start)
                double result = this.fВремяКонсульт;
                // *** Start programmer edit section *** (ОказУслуг.ВремяКонсульт Get end)

                // *** End programmer edit section *** (ОказУслуг.ВремяКонсульт Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОказУслуг.ВремяКонсульт Set start)

                // *** End programmer edit section *** (ОказУслуг.ВремяКонсульт Set start)
                this.fВремяКонсульт = value;
                // *** Start programmer edit section *** (ОказУслуг.ВремяКонсульт Set end)

                // *** End programmer edit section *** (ОказУслуг.ВремяКонсульт Set end)
            }
        }
        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (ОказУслуг.Дата CustomAttributes)

        // *** End programmer edit section *** (ОказУслуг.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (ОказУслуг.Дата Get start)

                // *** End programmer edit section *** (ОказУслуг.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (ОказУслуг.Дата Get end)

                // *** End programmer edit section *** (ОказУслуг.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОказУслуг.Дата Set start)

                // *** End programmer edit section *** (ОказУслуг.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (ОказУслуг.Дата Set end)

                // *** End programmer edit section *** (ОказУслуг.Дата Set end)
            }
        }
        
        /// <summary>
        /// ЕдВремени.
        /// </summary>
        // *** Start programmer edit section *** (ОказУслуг.ЕдВремени CustomAttributes)

        // *** End programmer edit section *** (ОказУслуг.ЕдВремени CustomAttributes)
        public virtual IIS.Modul_ucheta.ЕдВремени ЕдВремени
        {
            get
            {
                // *** Start programmer edit section *** (ОказУслуг.ЕдВремени Get start)

                // *** End programmer edit section *** (ОказУслуг.ЕдВремени Get start)
                IIS.Modul_ucheta.ЕдВремени result = this.fЕдВремени;
                // *** Start programmer edit section *** (ОказУслуг.ЕдВремени Get end)

                // *** End programmer edit section *** (ОказУслуг.ЕдВремени Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОказУслуг.ЕдВремени Set start)

                // *** End programmer edit section *** (ОказУслуг.ЕдВремени Set start)
                this.fЕдВремени = value;
                // *** Start programmer edit section *** (ОказУслуг.ЕдВремени Set end)

                // *** End programmer edit section *** (ОказУслуг.ЕдВремени Set end)
            }
        }
        
        /// <summary>
        /// Оказ услуг.
        /// </summary>
        // *** Start programmer edit section *** (ОказУслуг.Договор CustomAttributes)

        // *** End programmer edit section *** (ОказУслуг.Договор CustomAttributes)
        [PropertyStorage(new string[] {
                "Договор"})]
        [NotNull()]
        public virtual IIS.Modul_ucheta.Договор Договор
        {
            get
            {
                // *** Start programmer edit section *** (ОказУслуг.Договор Get start)

                // *** End programmer edit section *** (ОказУслуг.Договор Get start)
                IIS.Modul_ucheta.Договор result = this.fДоговор;
                // *** Start programmer edit section *** (ОказУслуг.Договор Get end)

                // *** End programmer edit section *** (ОказУслуг.Договор Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОказУслуг.Договор Set start)

                // *** End programmer edit section *** (ОказУслуг.Договор Set start)
                this.fДоговор = value;
                // *** Start programmer edit section *** (ОказУслуг.Договор Set end)

                // *** End programmer edit section *** (ОказУслуг.Договор Set end)
            }
        }
        
        /// <summary>
        /// Оказ услуг.
        /// </summary>
        // *** Start programmer edit section *** (ОказУслуг.Услуги CustomAttributes)

        // *** End programmer edit section *** (ОказУслуг.Услуги CustomAttributes)
        [PropertyStorage(new string[] {
                "Услуги"})]
        [NotNull()]
        public virtual IIS.Modul_ucheta.Услуги Услуги
        {
            get
            {
                // *** Start programmer edit section *** (ОказУслуг.Услуги Get start)

                // *** End programmer edit section *** (ОказУслуг.Услуги Get start)
                IIS.Modul_ucheta.Услуги result = this.fУслуги;
                // *** Start programmer edit section *** (ОказУслуг.Услуги Get end)

                // *** End programmer edit section *** (ОказУслуг.Услуги Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОказУслуг.Услуги Set start)

                // *** End programmer edit section *** (ОказУслуг.Услуги Set start)
                this.fУслуги = value;
                // *** Start programmer edit section *** (ОказУслуг.Услуги Set end)

                // *** End programmer edit section *** (ОказУслуг.Услуги Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Modul_ucheta.РасчетОстВрем.
        /// </summary>
        // *** Start programmer edit section *** (ОказУслуг.РасчетОстВрем CustomAttributes)

        // *** End programmer edit section *** (ОказУслуг.РасчетОстВрем CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "РасчетОстВрем"})]
        public virtual IIS.Modul_ucheta.РасчетОстВрем РасчетОстВрем
        {
            get
            {
                // *** Start programmer edit section *** (ОказУслуг.РасчетОстВрем Get start)

                // *** End programmer edit section *** (ОказУслуг.РасчетОстВрем Get start)
                IIS.Modul_ucheta.РасчетОстВрем result = this.fРасчетОстВрем;
                // *** Start programmer edit section *** (ОказУслуг.РасчетОстВрем Get end)

                // *** End programmer edit section *** (ОказУслуг.РасчетОстВрем Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОказУслуг.РасчетОстВрем Set start)

                // *** End programmer edit section *** (ОказУслуг.РасчетОстВрем Set start)
                this.fРасчетОстВрем = value;
                // *** Start programmer edit section *** (ОказУслуг.РасчетОстВрем Set end)

                // *** End programmer edit section *** (ОказУслуг.РасчетОстВрем Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОказУслугE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОказУслугE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОказУслугE", typeof(IIS.Modul_ucheta.ОказУслуг));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ОказУслуг.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfОказУслуг CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfОказУслуг CustomAttributes)
    public class DetailArrayOfОказУслуг : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Modul_ucheta.DetailArrayOfОказУслуг members)

        // *** End programmer edit section *** (IIS.Modul_ucheta.DetailArrayOfОказУслуг members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ОказУслуг by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ОказУслуг.
        /// </summary>
        public DetailArrayOfОказУслуг(IIS.Modul_ucheta.РасчетОстВрем fРасчетОстВрем) : 
                base(typeof(ОказУслуг), ((ICSSoft.STORMNET.DataObject)(fРасчетОстВрем)))
        {
        }
        
        public IIS.Modul_ucheta.ОказУслуг this[int index]
        {
            get
            {
                return ((IIS.Modul_ucheta.ОказУслуг)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Modul_ucheta.ОказУслуг dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
